const FACTIONS = ['Héros','Yakuza','Yamaguchi','Unbound','Breakout','Umbra','Triades'];
const ZONES = [
  {id:'laboratoire',name:'LABORATOIRE',num:'01',image:'assets/laboratoire.jpg'},
  {id:'dojo',name:'DOJO',num:'02',image:'assets/dojo.jpg'},
  {id:'casse',name:'CASSE',num:'03',image:'assets/casse.jpg'},
  {id:'maison-hantee',name:'MAISON HANTE',num:'04',image:'assets/maison-hantee.jpg'}
];
const KEY='i-island-v2';
let state=JSON.parse(localStorage.getItem(KEY)||'null') || {selected:null,zones:{}};
ZONES.forEach(z=>{if(!state.zones[z.id])state.zones[z.id]={owner:null,protectedUntil:null,history:[]};});
let raidTarget=null;
const ticker=document.getElementById('ticker'),selectedFaction=document.getElementById('selectedFaction'),territories=document.getElementById('territories'),modal=document.getElementById('raidModal'),toast=document.getElementById('toast');
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function formatTime(ms){let total=Math.max(0,Math.floor(ms/1000)),d=Math.floor(total/86400);total%=86400;let h=Math.floor(total/3600);total%=3600;let m=Math.floor(total/60),s=total%60;return `${String(d).padStart(2,'0')}J ${String(h).padStart(2,'0')}H ${String(m).padStart(2,'0')}M ${String(s).padStart(2,'0')}S`;}
function renderTicker(){ticker.innerHTML=FACTIONS.map(f=>`<button class="faction ${state.selected===f?'active':''}" data-faction="${escapeHtml(f)}">${escapeHtml(f)}</button>`).join('');document.querySelectorAll('.faction').forEach(b=>b.onclick=()=>{state.selected=b.dataset.faction;save();render();showToast(`${state.selected} sélectionné`);});selectedFaction.textContent=state.selected||'AUCUN';}
function render(){renderTicker();territories.innerHTML=ZONES.map(z=>{const d=state.zones[z.id];let remaining=d.protectedUntil?d.protectedUntil-Date.now():0;if(remaining<=0&&d.protectedUntil){d.protectedUntil=null;save();remaining=0;}const protectedNow=remaining>0;const canRaid=!!state.selected&&!protectedNow;const owner=d.owner?escapeHtml(d.owner):'<span class="empty-owner">PERSONNE</span>';const history=d.history.length?d.history.map(h=>`<span class="history-item">${escapeHtml(h)}</span>`).join(''):'<span class="history-item">AUCUN HISTORIQUE</span>';return `<article class="territory"><div class="territory-art" style="--image:url('${z.image}')"></div><span class="status-badge ${protectedNow?'protected':'free'}">${protectedNow?'SOUS PROTECTION':'RAID POSSIBLE'}</span><div class="territory-content"><div class="territory-number">SECTEUR ${z.num}</div><h3>${z.name}</h3><div><div class="owner-label">DÉTENTEUR ACTUEL</div><div class="owner">${owner}</div></div><div class="territory-bottom"><div class="protection"><span class="protection-label">${protectedNow?'PROTECTION RESTANTE':'STATUT'}</span><span class="countdown">${protectedNow?formatTime(remaining):'OUVERT'}</span></div><button class="danger raid-btn" data-zone="${z.id}" ${canRaid?'':'disabled'}>${state.selected?(protectedNow?'PROTECTION ACTIVE':'RAID '+z.name):'SÉLECTIONNE UN NOM'}</button></div><div class="history"><div class="history-title">ANCIENS DÉTENTEURS</div><div class="history-list">${history}</div></div></div></article>`;}).join('');document.querySelectorAll('.raid-btn:not(:disabled)').forEach(b=>b.onclick=()=>openRaid(b.dataset.zone));}
function openRaid(zoneId){raidTarget=zoneId;const z=ZONES.find(x=>x.id===zoneId),d=state.zones[zoneId];document.getElementById('modalTitle').textContent=`RAID — ${z.name}`;document.getElementById('modalText').textContent=`${state.selected} va prendre le contrôle de ${z.name}. ${d.owner?`Le détenteur actuel est ${d.owner}. Il restera enregistré comme ancien détenteur.`:'Ce territoire est actuellement libre.'} Une protection de 3 jours (72 heures) sera activée immédiatement.`;modal.classList.remove('hidden');}
function closeModal(){modal.classList.add('hidden');raidTarget=null;}
document.getElementById('confirmRaid').onclick=()=>{if(!raidTarget||!state.selected)return;const d=state.zones[raidTarget];if(d.owner&&d.owner!==state.selected)d.history.unshift(d.owner);d.history=[...new Set(d.history)].slice(0,8);d.owner=state.selected;d.protectedUntil=Date.now()+3*24*60*60*1000;save();const zoneName=ZONES.find(z=>z.id===raidTarget)?.name||'territoire';closeModal();render();showToast(`${state.selected} contrôle désormais ${zoneName}`);};
document.getElementById('cancelRaid').onclick=closeModal;document.getElementById('closeModal').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
document.getElementById('clearSelection').onclick=()=>{state.selected=null;save();render();showToast('Sélection effacée');};
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1800);}
setInterval(render,1000);render();
